### ISSUE TITLE
Existing interaction assertion raises a key error

### ISSUE THREAD

**Issue by MatthewMiele** [reecetech/pactman#28]
There is small typo in the assertion message for the existing interaction check.

https://github.com/reecetech/pactman/blob/master/pactman/mock/pact_request_handler.py#L107

```python
 assert existing == interaction, 'Existing "{existing["description"]}" pact given ' \
                        '{existing.get(provider_state_key)!r} exists with different request/response'.format(**locals())
```

When this assertion is triggered is raises ``` KeyError: '"description"'``` due to the `description` being inside quotes in the string when it shouldn't be.

Correct line
```python
 assert existing == interaction, 'Existing "{existing[description]}" pact given ' \
                        '{existing.get(provider_state_key)!r} exists with different request/response'.format(**locals())
```

**Comment by richard-reece** [comment]
Looks like a strange difference between .format() and f-strings. I'll correct it in the next patch, thanks!

```python
Python 3.6.5 (default, Dec 31 2018, 10:42:29) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = dict(d=1)
>>> '{d[d]}'.format(**locals())
'1'
>>> '{d["d"]}'.format(**locals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '"d"'
>>> f'{d["d"]}'
'1'
>>> f'{d[d]}'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'
>>> 
```
